# Generated by Django 3.1.3 on 2020-11-24 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('postnom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('societe', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_contacts',
            },
        ),
    ]
